use_frameworks!



platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'  # 官方库
source 'https://github.com/nadeal/geraSpecs.git'

target 'BusAKit_Example' do
  pod 'BusAKit', :path => '../'
  pod 'YakerKit'

  target 'BusAKit_Tests' do
    inherit! :search_paths

    
  end
end
